name: Release
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-darwin-amd64-20.0.0.tar.gz
            artifact: scalafmt-macos
            bazel_installer_sha: b4c94148f52854b89cff5de38a9eeeb4b0bcb3fb3a027330c46c468d9ea0898b
            bazel_version: 2.1.1
          - os: ubuntu-latest
            url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
            artifact: scalafmt-linux
            bazel_installer_sha: d6cea18d59e9c90c7ec417b2645834f968132de16d0022c7439b1e60438eb8c9
            bazel_version: 2.1.1
    steps:
      - uses: actions/checkout@v2
      - name: Bazel output cache
        id: cache-bazel
        uses: actions/cache@v1
        with:
          path: "${{ github.workspace }}/.bazel-cache"
          key: ${{ runner.os }}-bazel-out-${{ github.run_id}}
          restore-keys: |
            ${{ runner.os }}-bazel-out-
      - name: Configure bazel config for actions
      run: |
        echo "build --config github_actions" > user.bazelrc
        echo "build --disk_cache ${{ github.workspace }}/.bazel-cache/disk-cache" >> user.bazelrc
        echo "build --repository_cache ${{ github.workspace }}/.bazel-cache/repo-cache" >> user.bazelrc
      - name: Install bazel
        run: ./ci_scripts/ci_install_bazel.sh
        env:
          BAZEL_VERSION: ${{ matrix.bazel_version }}
          BAZEL_INSTALLER_SHA: ${{ matrix.bazel_installer_sha }}
          BAZEL_BIN_LOC: "${{ github.workspace }}/.bazel-cache/bazel-bin"
      - name: Build fat jar
        run: ./ci_scripts/build_fat_jar.sh
        env:
          BAZEL_VERSION: ${{ matrix.bazel_version }}
          BAZEL_INSTALLER_SHA: ${{ matrix.bazel_installer_sha }}
          BAZEL_BIN_LOC: "${{ github.workspace }}/.bazel-cache/bazel-bin"
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: scalafmt
  make_release:
    name: Display results
    needs: native-image
    runs-on: ubuntu-latest
    steps:
      - name: Download linux scalafmt
        uses: actions/download-artifact@v1
        with:
          name: scalafmt-linux
          path: downloads/scalafmt-linux
      - name: Download linux scalafmt
        uses: actions/download-artifact@v1
        with:
          name: scalafmt-macos
          path: downloads/scalafmt-macos
      - name: Look at localA
        run: ls -lR
      - name: mv binaries linux
        run: mv downloads/scalafmt-linux/scalafmt scalafmt-linux
      - name: mv binaries macos
        run: mv downloads/scalafmt-macos/scalafmt scalafmt-macos
      - name: Look at local
        run: ls -lR
      - name: Look at macos
        run: cat scalafmt-macos
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.1-${{ github.run_number }}"
          prerelease: false
          title: "Auto generated release"
          files: |
            scalafmt-macos
            scalafmt-linux
        id: "automatic_releases"
